### ISSUE TITLE
Kernel error while starting

### ISSUE THREAD

**Issue by brut0** [jupyter-xeus/xeus-python#239]
I create jupyterlab-debugger. Then install xeus-python from conda promt on Windows 10 using this command:
`conda install xeus-python notebook -c conda-forge`
After running Jupyter Notebook and staring kernel I see "Kernel error" with this message

> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\tornado\web.py", line 1703, in _execute
>     result = await result
>   File "C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\tornado\gen.py", line 742, in run
>     yielded = self.gen.throw(*exc_info)  # type: ignore
>   File "C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
>     type=mtype))
>   File "C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\tornado\gen.py", line 735, in run
>     value = future.result()
>   File "C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\tornado\gen.py", line 742, in run
>     yielded = self.gen.throw(*exc_info)  # type: ignore
>   File "C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
>     kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
>   File "C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\tornado\gen.py", line 735, in run
>     value = future.result()
>   File "C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\tornado\gen.py", line 742, in run
>     yielded = self.gen.throw(*exc_info)  # type: ignore
>   File "C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
>     self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
>   File "C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\tornado\gen.py", line 735, in run
>     value = future.result()
>   File "C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\tornado\gen.py", line 209, in wrapper
>     yielded = next(result)
>   File "C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
>     super(MappingKernelManager, self).start_kernel(**kwargs)
>   File "C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\jupyter_client\multikernelmanager.py", line 158, in start_kernel
>     km.start_kernel(**kwargs)
>   File "C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\jupyter_client\manager.py", line 305, in start_kernel
>     self.kernel = self._launch_kernel(kernel_cmd, **kw)
>   File "C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\jupyter_client\manager.py", line 212, in _launch_kernel
>     return launch_kernel(kernel_cmd, **kw)
>   File "C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\jupyter_client\launcher.py", line 135, in launch_kernel
>     proc = Popen(cmd, **kwargs)
>   File "C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\lib\subprocess.py", line 800, in __init__
>     restore_signals, start_new_session)
>   File "C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\lib\subprocess.py", line 1207, in _execute_child
>     startupinfo)
> FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by SylvainCorlay** [comment]
Hi @brut0, thanks for posting.

Could you please report what ` jupyter kernelspec list` returns, and the content of the kernel.json corresponding to the xpython entry listed there?

**Comment by brut0** [comment]
Available kernels:
>   python3    C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\share\jupyter\kernels\python3
>   xpython    C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\share\jupyter\kernels\xpython

kernel.json:
```
{
  "display_name": "xpython",
  "argv": [
      "D:/bld/xeus-python_1585147714833/_h_env/Library/bin/xpython",
      "-f",
      "{connection_file}"
  ],
  "language": "python"
}
```

It seems that path to interpreter is wrong. I change path to

> C:/ProgramData/Anaconda3/envs/jupyterlab-debugger/Library/bin\\xpython.exe

After that another error message is shown

> A connection to the notebook server could not be established. The notebook will continue trying to reconnect. Check your network connection or notebook server configuration.

**Comment by SylvainCorlay** [comment]
>       "D:/bld/xeus-python_1585147714833/_h_env/Library/bin/xpython",

It seems that the conda package manager did not properly perform the relocation unfortunately. This is weird because we rely on this heavily and it is supposed to work.

> another error message is shown

Can you show the content of the console where the server is started?

**Comment by SylvainCorlay** [comment]
OK, the relocation issue of `kernel.json` is due to the fact that this conda package was built with conda-build 3.19 which happens to be completely broken.

https://github.com/conda-forge/cf-mark-broken/pull/31

**Comment by SylvainCorlay** [comment]
@brut0 can you try by pinning xeus-python 0.6.12 which was built with a non-broken conda-build?

**Comment by brut0** [comment]
Console content from jupyter start until kernel connection error
(sorry if it is too big)
> [I 21:12:43.054 NotebookApp] The port 8888 is already in use, trying another port.
> [I 21:12:43.054 NotebookApp] The port 8889 is already in use, trying another port.
> [I 21:12:43.055 NotebookApp] The port 8890 is already in use, trying another port.
> [I 21:12:43.764 NotebookApp] JupyterLab extension loaded from C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\jupyterlab
> [I 21:12:43.764 NotebookApp] JupyterLab application directory is C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab
> [I 21:12:43.767 NotebookApp] Serving notebooks from local directory: C:\Users\Сергей
> [I 21:12:43.767 NotebookApp] The Jupyter Notebook is running at:
> [I 21:12:43.767 NotebookApp] http://localhost:8891/?token=0f77eea918cd42336b6511cca623868c74fcebb96ee31db2
> [I 21:12:43.768 NotebookApp]  or http://127.0.0.1:8891/?token=0f77eea918cd42336b6511cca623868c74fcebb96ee31db2
> [I 21:12:43.768 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
> [C 21:12:43.894 NotebookApp] 
>     To access the notebook, open this file in a browser: file:///C:/Users/%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B9/AppData/Roaming/jupyter/runtime/nbserver-5160-open.html
>     Or copy and paste one of these URLs:
>         http://localhost:8891/?token=0f77eea918cd42336b6511cca623868c74fcebb96ee31db2
>      or http://127.0.0.1:8891/?token=0f77eea918cd42336b6511cca623868c74fcebb96ee31db2
> [I 21:13:25.785 NotebookApp] 302 GET /?token=0f77eea918cd42336b6511cca623868c74fcebb96ee31db2 (::1) 1.00ms
> [I 21:13:31.248 NotebookApp] Creating new notebook in 
> [I 21:13:32.236 NotebookApp] Kernel started: ab38c4e9-071b-4e91-93f5-78429fcfad02
> [W 21:13:32.255 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20200331211242 (::1) 14.99ms referer=http://localhost:8891/notebooks/Untitled1.ipynb?kernel_name=xpython
> PYTHONHOME set to C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin\..\..\
> Python sys.path set to C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\python37.zip;C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin\..\..\\DLLs;C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin\..\..\\lib;C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin
> [I 21:13:35.228 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
> PYTHONHOME set to C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin\..\..\
> Python sys.path set to C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\python37.zip;C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin\..\..\\DLLs;C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin\..\..\\lib;C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin
> [I 21:13:38.221 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
> PYTHONHOME set to C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin\..\..\
> Python sys.path set to C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\python37.zip;C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin\..\..\\DLLs;C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin\..\..\\lib;C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin
> [I 21:13:41.225 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
> PYTHONHOME set to C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin\..\..\
> Python sys.path set to C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\python37.zip;C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin\..\..\\DLLs;C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin\..\..\\lib;C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin
> [I 21:13:44.232 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
> PYTHONHOME set to C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin\..\..\
> Python sys.path set to C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\python37.zip;C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin\..\..\\DLLs;C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin\..\..\\lib;C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin
> [W 21:13:47.240 NotebookApp] KernelRestarter: restart failed
> [W 21:13:47.240 NotebookApp] Kernel ab38c4e9-071b-4e91-93f5-78429fcfad02 died, removing from map.
> [W 21:14:32.254 NotebookApp] Timeout waiting for kernel_info reply from ab38c4e9-071b-4e91-93f5-78429fcfad02
> [E 21:14:32.255 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: ab38c4e9-071b-4e91-93f5-78429fcfad02)
> [W 21:14:33.942 NotebookApp] 404 GET /api/kernels/ab38c4e9-071b-4e91-93f5-78429fcfad02/channels?session_id=2fc296bb79384ddcb8277c7e7e0e50f7 (::1): Kernel does not exist: ab38c4e9-071b-4e91-93f5-78429fcfad02
> [W 21:14:33.943 NotebookApp] 404 GET /api/kernels/ab38c4e9-071b-4e91-93f5-78429fcfad02/channels?session_id=2fc296bb79384ddcb8277c7e7e0e50f7 (::1) 3.00ms referer=None
> [W 21:14:36.944 NotebookApp] Replacing stale connection: ab38c4e9-071b-4e91-93f5-78429fcfad02:2fc296bb79384ddcb8277c7e7e0e50f7

**Comment by SylvainCorlay** [comment]
OK, I suspect that the conda package for 0.6.13 is broken in several ways because of that conda bug.

Let me know if reverting to 0.6.12 fixes your issue. (I just tested locally and all is fine).

I am making a new build of 0.6.13.

**Comment by brut0** [comment]
I reverted to 0.6.12. Now kernel.json looks like:
```
{
  "display_name": "xpython",
  "argv": [
      "C:/ProgramData/Anaconda3/envs/jupyterlab-debugger/Library/bin/xpython",
      "-f",
      "{connection_file}"
  ],
  "language": "python"
}
```

But, connection to kernel failed anyway:

> [I 21:30:49.149 NotebookApp] The port 8888 is already in use, trying another port.
> [I 21:30:49.150 NotebookApp] The port 8889 is already in use, trying another port.
> [I 21:30:49.150 NotebookApp] The port 8890 is already in use, trying another port.
> [I 21:30:49.868 NotebookApp] JupyterLab extension loaded from C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\jupyterlab
> [I 21:30:49.868 NotebookApp] JupyterLab application directory is C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab
> [I 21:30:49.871 NotebookApp] Serving notebooks from local directory: C:\Users\Сергей
> [I 21:30:49.871 NotebookApp] The Jupyter Notebook is running at:
> [I 21:30:49.871 NotebookApp] http://localhost:8891/?token=72b3a53da0abc1dc21d855666f1829f823cec8cfc663c93a
> [I 21:30:49.871 NotebookApp]  or http://127.0.0.1:8891/?token=72b3a53da0abc1dc21d855666f1829f823cec8cfc663c93a
> [I 21:30:49.871 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
> [C 21:30:49.996 NotebookApp] 
>     ...
> [I 21:30:59.915 NotebookApp] Creating new notebook in 
> [I 21:31:01.179 NotebookApp] Kernel started: e79286ab-04aa-4198-a0da-0673a709f8bc
> [W 21:31:01.197 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20200331213048 (127.0.0.1) 15.99ms referer=http://127.0.0.1:8891/notebooks/Untitled2.ipynb?kernel_name=xpython
> PYTHONHOME set to C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin\..\..\
> [I 21:31:04.162 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
> PYTHONHOME set to C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin\..\..\
> [I 21:31:07.161 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
> PYTHONHOME set to C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin\..\..\
> [I 21:31:10.170 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
> PYTHONHOME set to C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin\..\..\
> [I 21:31:13.178 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
> PYTHONHOME set to C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin\..\..\
> [W 21:31:16.185 NotebookApp] KernelRestarter: restart failed
> [W 21:31:16.185 NotebookApp] Kernel e79286ab-04aa-4198-a0da-0673a709f8bc died, removing from map.
> [W 21:32:01.214 NotebookApp] Timeout waiting for kernel_info reply from e79286ab-04aa-4198-a0da-0673a709f8bc
> [E 21:32:01.215 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: e79286ab-04aa-4198-a0da-0673a709f8bc)
> [W 21:32:02.235 NotebookApp] 404 GET /api/kernels/e79286ab-04aa-4198-a0da-0673a709f8bc/channels?session_id=4d3d6fcb3eba4f5296404103d42bd65e (127.0.0.1): Kernel does not exist: e79286ab-04aa-4198-a0da-0673a709f8bc
> [W 21:32:02.237 NotebookApp] 404 GET /api/kernels/e79286ab-04aa-4198-a0da-0673a709f8bc/channels?session_id=4d3d6fcb3eba4f5296404103d42bd65e (127.0.0.1) 3.00ms referer=None

**Comment by SylvainCorlay** [comment]
If you just run `xpython`  in your environment what do you see?

**Comment by brut0** [comment]
`xpython` does not run.
only this message has been shown:

> PYTHONHOME set to C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin\..\..\
> Starting xeus-python kernel...
> 
> If you want to connect to this kernel from an other client, just copy and paste the following content inside of a `kernel.json` file. And then run for example:
> 
> \# jupyter console --existing kernel.json
> 
> kernel.json
> ```
> {
>     "transport": "tcp",
>     "ip": "127.0.0.1",
>     "control_port": 58300 ,
>     "shell_port": 51018 ,
>     "stdin_port": 55647 ,
>     "iopub_port": 50916 ,
>     "hb_port": 63521 ,
>     "signature_scheme": "hmac-sha256",
>     "key": "c95b591e24504a71a162a39cdfa96af9"
> }
> ```

**Comment by SylvainCorlay** [comment]
Ok, that means it does run. This is the expected behavior (to show the connection information). In your logs, the lines

```
Python sys.path set to C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\python37.zip;C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin....\DLLs;C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin....\lib;C:\ProgramData\Anaconda3\envs\jupyterlab-debugger\Library\bin
```

correspont to some logs we print when starting the kernel. So somethings makes it crash at a later stage.

Could you please report the output of `conda list` in your environment?

**Comment by brut0** [comment]
@SylvainCorlay, thanks for clarifying.

Output of `conda list`:

> \# packages in environment at C:\ProgramData\Anaconda3\envs\jupyterlab-debugger:
> \# Name                    Version                   Build  Channel
> attrs                     19.3.0                     py_0    conda-forge
> backcall                  0.1.0                      py_0    conda-forge
> bleach                    3.1.4              pyh9f0ad1d_0    conda-forge
> ca-certificates           2019.11.28           hecc5488_0    conda-forge
> certifi                   2019.11.28       py37hc8dfbb8_1    conda-forge
> cffi                      1.14.0           py37ha419a9e_0    conda-forge
> chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
> cmake                     3.17.0               he025d50_0    conda-forge
> colorama                  0.4.3                      py_0    conda-forge
> cryptography              2.8              py37hb32ad35_1    conda-forge
> decorator                 4.4.2                      py_0    conda-forge
> defusedxml                0.6.0                      py_0    conda-forge
> entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
> idna                      2.9                        py_1    conda-forge
> importlib-metadata        1.6.0            py37hc8dfbb8_0    conda-forge
> importlib_metadata        1.6.0                         0    conda-forge
> ipykernel                 5.2.0            py37h5ca1d4c_1    conda-forge
> ipython                   7.13.0           py37hc8dfbb8_2    conda-forge
> ipython_genutils          0.2.0                      py_1    conda-forge
> jedi                      0.15.2                   py37_0    conda-forge
> jinja2                    2.11.1                     py_0    conda-forge
> json5                     0.9.0                      py_0    conda-forge
> jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
> jupyter_client            6.1.2                      py_0    conda-forge
> jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
> jupyterlab                2.0.1                      py_0    conda-forge
> jupyterlab_server         1.1.0                      py_0    conda-forge
> libsodium                 1.0.17               h2fa13f4_0    conda-forge
> m2w64-gcc-libgfortran     5.3.0                         6  
> m2w64-gcc-libs            5.3.0                         7  
> m2w64-gcc-libs-core       5.3.0                         7  
> m2w64-gmp                 6.1.0                         2  
> m2w64-libwinpthread-git   5.0.0.4634.697f757               2  
> markupsafe                1.1.1            py37h8055547_1    conda-forge
> mistune                   0.8.4           py37hfa6e2cd_1000    conda-forge
> msys2-conda-epoch         20160418                      1  
> nbconvert                 5.6.1                    py37_0    conda-forge
> nbformat                  5.0.4                      py_0    conda-forge
> nlohmann_json             3.7.3                he025d50_1    conda-forge
> notebook                  6.0.3                    py37_0    conda-forge
> openssl                   1.1.1f               hfa6e2cd_0    conda-forge
> pandoc                    2.9.2                         0    conda-forge
> pandocfilters             1.4.2                      py_1    conda-forge
> parso                     0.6.2                      py_0    conda-forge
> pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
> pip                       20.0.2                     py_2    conda-forge
> prometheus_client         0.7.1                      py_0    conda-forge
> prompt-toolkit            3.0.5                      py_0    conda-forge
> ptvsd                     4.3.2            py37hfa6e2cd_1    conda-forge
> pybind11_json             0.2.4            py37heaa310e_1    conda-forge
> pycparser                 2.20                       py_0    conda-forge
> pygments                  2.6.1                      py_0    conda-forge
> pyopenssl                 19.1.0                     py_1    conda-forge
> pyrsistent                0.16.0           py37h8055547_0    conda-forge
> pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
> python                    3.7.6           h60c2a47_5_cpython    conda-forge
> python-dateutil           2.8.1                      py_0    conda-forge
> python_abi                3.7                     1_cp37m    conda-forge
> pywin32                   227              py37hfa6e2cd_0    conda-forge
> pywinpty                  0.5.7                    py37_0    conda-forge
> pyzmq                     19.0.0           py37h8c16cda_1    conda-forge
> requests                  2.23.0             pyh8c360ce_2    conda-forge
> send2trash                1.5.0                      py_0    conda-forge
> setuptools                46.1.3           py37hc8dfbb8_0    conda-forge
> six                       1.14.0                     py_1    conda-forge
> sqlite                    3.30.1               hfa6e2cd_0    conda-forge
> terminado                 0.8.3            py37hc8dfbb8_1    conda-forge
> testpath                  0.4.4                      py_0    conda-forge
> tornado                   6.0.4            py37hfa6e2cd_0    conda-forge
> traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
> urllib3                   1.25.7           py37hc8dfbb8_1    conda-forge
> vc                        14.1                 h869be7e_1    conda-forge
> vs2015_runtime            14.16.27012          h30e32a0_1    conda-forge
> wcwidth                   0.1.9              pyh9f0ad1d_0    conda-forge
> webencodings              0.5.1                      py_1    conda-forge
> wheel                     0.34.2                     py_1    conda-forge
> win_inet_pton             1.1.0                    py37_0    conda-forge
> wincertstore              0.2                   py37_1003    conda-forge
> winpty                    0.4.3                         4    conda-forge
> xeus                      0.23.10              h1ad3211_0    conda-forge
> xeus-python               0.6.12           py37h1ad3211_1    conda-forge
> xtl                       0.6.13               h1ad3211_0    conda-forge
> zeromq                    4.3.2                h6538335_2    conda-forge
> zipp                      3.1.0                      py_0    conda-forge
>

**Comment by brut0** [comment]
I reinstalled xeus python and jupyterlab in new environment using this command
`conda create -n jupyterlab-debugger -c conda-forge xeus-python=0.6.12 notebook=6 jupyterlab=2 ptvsd`

But, the problem is same

kernel.json:
```
{
  "display_name": "xpython",
  "argv": [
      "C:/ProgramData/Anaconda3/envs/xpython-debugger/Library/bin/xpython",
      "-f",
      "{connection_file}"
  ],
  "language": "python"
}
```

Output of Jupyter Notebook:

> [I 20:40:50.279 NotebookApp] Kernel started: 7e4e2f5d-ec04-402c-99d3-7032dc2322d0
> PYTHONHOME set to C:\ProgramData\Anaconda3\envs\xpython-debugger\Library\bin\..\..\
> [I 20:40:53.279 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
> PYTHONHOME set to C:\ProgramData\Anaconda3\envs\xpython-debugger\Library\bin\..\..\
> [I 20:40:56.287 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
> PYTHONHOME set to C:\ProgramData\Anaconda3\envs\xpython-debugger\Library\bin\..\..\
> [I 20:40:59.288 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
> PYTHONHOME set to C:\ProgramData\Anaconda3\envs\xpython-debugger\Library\bin\..\..\
> [I 20:41:02.297 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
> PYTHONHOME set to C:\ProgramData\Anaconda3\envs\xpython-debugger\Library\bin\..\..\
> [W 20:41:05.305 NotebookApp] KernelRestarter: restart failed
> [W 20:41:05.305 NotebookApp] Kernel 7e4e2f5d-ec04-402c-99d3-7032dc2322d0 died, removing from map.
> [W 20:41:50.287 NotebookApp] Timeout waiting for kernel_info reply from 7e4e2f5d-ec04-402c-99d3-7032dc2322d0
> [E 20:41:50.288 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 7e4e2f5d-ec04-402c-99d3-7032dc2322d0)
> [W 20:41:51.307 NotebookApp] 404 GET /api/kernels/7e4e2f5d-ec04-402c-99d3-7032dc2322d0/channels?session_id=48e5e6b561eb4f6fb970d91ab00bbb83 (::1): Kernel does not exist: 7e4e2f5d-ec04-402c-99d3-7032dc2322d0
> [W 20:41:51.308 NotebookApp] 404 GET /api/kernels/7e4e2f5d-ec04-402c-99d3-7032dc2322d0/channels?session_id=48e5e6b561eb4f6fb970d91ab00bbb83 (::1) 3.00ms referer=None

`conda list`

> \# packages in environment at C:\ProgramData\Anaconda3\envs\xpython-debugger:
> \# Name                    Version                   Build  Channel
> attrs                     19.3.0                     py_0    conda-forge
> backcall                  0.1.0                      py_0    conda-forge
> bleach                    3.1.4              pyh9f0ad1d_0    conda-forge
> ca-certificates           2019.11.28           hecc5488_0    conda-forge
> certifi                   2019.11.28       py37hc8dfbb8_1    conda-forge
> cffi                      1.14.0           py37ha419a9e_0    conda-forge
> chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
> colorama                  0.4.3                      py_0    conda-forge
> cryptography              2.8              py37hb32ad35_1    conda-forge
> decorator                 4.4.2                      py_0    conda-forge
> defusedxml                0.6.0                      py_0    conda-forge
> entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
> idna                      2.9                        py_1    conda-forge
> importlib-metadata        1.6.0            py37hc8dfbb8_0    conda-forge
> importlib_metadata        1.6.0                         0    conda-forge
> ipykernel                 5.2.0            py37h5ca1d4c_1    conda-forge
> ipython                   7.13.0           py37hc8dfbb8_2    conda-forge
> ipython_genutils          0.2.0                      py_1    conda-forge
> jedi                      0.15.2                   py37_0    conda-forge
> jinja2                    2.11.1                     py_0    conda-forge
> json5                     0.9.0                      py_0    conda-forge
> jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
> jupyter_client            6.1.2                      py_0    conda-forge
> jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
> jupyterlab                2.0.1                      py_0    conda-forge
> jupyterlab_server         1.1.0                      py_0    conda-forge
> libsodium                 1.0.17               h2fa13f4_0    conda-forge
> m2w64-gcc-libgfortran     5.3.0                         6  
> m2w64-gcc-libs            5.3.0                         7  
> m2w64-gcc-libs-core       5.3.0                         7  
> m2w64-gmp                 6.1.0                         2  
> m2w64-libwinpthread-git   5.0.0.4634.697f757               2  
> markupsafe                1.1.1            py37h8055547_1    conda-forge
> mistune                   0.8.4           py37hfa6e2cd_1000    conda-forge
> msys2-conda-epoch         20160418                      1  
> nbconvert                 5.6.1                    py37_0    conda-forge
> nbformat                  5.0.4                      py_0    conda-forge
> notebook                  6.0.3                    py37_0    conda-forge
> openssl                   1.1.1f               hfa6e2cd_0    conda-forge
> pandoc                    2.9.2                         0    conda-forge
> pandocfilters             1.4.2                      py_1    conda-forge
> parso                     0.6.2                      py_0    conda-forge
> pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
> pip                       20.0.2                     py_2    conda-forge
> prometheus_client         0.7.1                      py_0    conda-forge
> prompt-toolkit            3.0.5                      py_0    conda-forge
> ptvsd                     4.3.2            py37hfa6e2cd_1    conda-forge
> pycparser                 2.20                       py_0    conda-forge
> pygments                  2.6.1                      py_0    conda-forge
> pyopenssl                 19.1.0                     py_1    conda-forge
> pyrsistent                0.16.0           py37h8055547_0    conda-forge
> pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
> python                    3.7.6           h60c2a47_5_cpython    conda-forge
> python-dateutil           2.8.1                      py_0    conda-forge
> python_abi                3.7                     1_cp37m    conda-forge
> pywin32                   227              py37hfa6e2cd_0    conda-forge
> pywinpty                  0.5.7                    py37_0    conda-forge
> pyzmq                     19.0.0           py37h8c16cda_1    conda-forge
> requests                  2.23.0             pyh8c360ce_2    conda-forge
> send2trash                1.5.0                      py_0    conda-forge
> setuptools                46.1.3           py37hc8dfbb8_0    conda-forge
> six                       1.14.0                     py_1    conda-forge
> sqlite                    3.30.1               hfa6e2cd_0    conda-forge
> terminado                 0.8.3            py37hc8dfbb8_1    conda-forge
> testpath                  0.4.4                      py_0    conda-forge
> tornado                   6.0.4            py37hfa6e2cd_0    conda-forge
> traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
> urllib3                   1.25.7           py37hc8dfbb8_1    conda-forge
> vc                        14.1                 h869be7e_1    conda-forge
> vs2015_runtime            14.16.27012          h30e32a0_1    conda-forge
> wcwidth                   0.1.9              pyh9f0ad1d_0    conda-forge
> webencodings              0.5.1                      py_1    conda-forge
> wheel                     0.34.2                     py_1    conda-forge
> win_inet_pton             1.1.0                    py37_0    conda-forge
> wincertstore              0.2                   py37_1003    conda-forge
> winpty                    0.4.3                         4    conda-forge
> xeus                      0.23.10              h1ad3211_0    conda-forge
> xeus-python               0.6.12           py37h1ad3211_1    conda-forge
> zeromq                    4.3.2                h6538335_2    conda-forge
> zipp                      3.1.0                      py_0    conda-forge

**Comment by SylvainCorlay** [comment]
@brut0 I don't know what is the problem here as we are not reproducing. Marked the issue as "Bug".
