### ISSUE TITLE
Autocomplete broken in jupyter console

### ISSUE THREAD

**Issue by CarlAndersson** [jupyter-xeus/xeus-python#387]
After installing xeus-python and jupyter_console in a clean conda environment, autocompletions seems to be broken when connecting the jupyter console to the xeus kernel.

Typing some partial variable name and pressing tab, nothing happens. As soon as another command is entered, the console crashes but the kernel is still up and can be reconnected to.

Crash trace
```
keeping kernel alive
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<ZMQTerminalInteractiveShell.interact() done, defined at /Users/carl/miniconda3/envs/xeus-test/lib/python3.9/site-packages/jupyter_console/ptshell.py:636> exception=KeyError('metadata')>
Traceback (most recent call last):
  File "/Users/carl/miniconda3/envs/xeus-test/lib/python3.9/site-packages/jupyter_console/ptshell.py", line 641, in interact
    code = await self.prompt_for_code()
  File "/Users/carl/miniconda3/envs/xeus-test/lib/python3.9/site-packages/jupyter_console/ptshell.py", line 584, in prompt_for_code
    text = await self.pt_cli.prompt_async(default=default)
  File "/Users/carl/miniconda3/envs/xeus-test/lib/python3.9/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1195, in prompt_async
    return await self.app.run_async(set_exception_handler=set_exception_handler)
  File "/Users/carl/miniconda3/envs/xeus-test/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 783, in run_async
    return await _run_async2()
  File "/Users/carl/miniconda3/envs/xeus-test/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 771, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/Users/carl/miniconda3/envs/xeus-test/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 872, in cancel_and_wait_for_background_tasks
    await task
  File "/Users/carl/miniconda3/envs/xeus-test/lib/python3.9/site-packages/prompt_toolkit/buffer.py", line 1854, in new_coroutine
    await coroutine(*a, **kw)
  File "/Users/carl/miniconda3/envs/xeus-test/lib/python3.9/site-packages/prompt_toolkit/buffer.py", line 1683, in async_completer
    async for completion in self.completer.get_completions_async(
  File "/Users/carl/miniconda3/envs/xeus-test/lib/python3.9/site-packages/prompt_toolkit/completion/base.py", line 269, in get_completions_async
    async for completion in completer.get_completions_async(
  File "/Users/carl/miniconda3/envs/xeus-test/lib/python3.9/site-packages/prompt_toolkit/completion/base.py", line 196, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/Users/carl/miniconda3/envs/xeus-test/lib/python3.9/site-packages/jupyter_console/ptshell.py", line 153, in get_completions
    meta = content["metadata"]
KeyError: 'metadata'
```

Package list
```
appnope                   0.1.2            py39h6e9494a_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
ca-certificates           2020.12.8            hecd8cb5_0
certifi                   2020.12.5        py39h6e9494a_1    conda-forge
debugpy                   1.2.1            py39h81cd7d3_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
ipykernel                 5.4.2            py39h71a6800_0    conda-forge
ipython                   7.19.0           py39h71a6800_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.0           py39h6e9494a_2    conda-forge
jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
jupyter_console           6.2.0                      py_0    conda-forge
jupyter_core              4.7.0            py39h6e9494a_0    conda-forge
libcxx                    11.0.0               h4c3b8ed_1    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
openssl                   1.1.1i               h35c211d_0    conda-forge
parso                     0.8.1              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.10             pyha770c72_0    conda-forge
prompt_toolkit            3.0.10               hd8ed1ab_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pygments                  2.7.4              pyhd3eb1b0_0
python                    3.9.1           h1d169a7_3_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pyzmq                     21.0.0           py39hd6373f1_0    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
setuptools                51.1.2           py39hecd8cb5_4
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h17101e1_0    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
tornado                   6.1              py39hcbf5805_1    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
tzdata                    2020f                he74cb21_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xeus                      0.25.3               h6daa668_1    conda-forge
xeus-python               0.9.5            py39h3e409ef_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zeromq                    4.3.3                h74dc148_3    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
```

**Comment by JohanMabille** [comment]
Thanks for reporting! Il will publish a fix tonight.
