### ISSUE TITLE
Should the debugger check validity of expressions passed to `richInspectVariables`

### ISSUE THREAD

**Issue by krassowski** [jupyter-xeus/xeus-python#475]
Currently wee can get a syntax error like:

```
Error processing internal command.
Traceback (most recent call last):
  File "/home/krassowski/miniconda3/envs/xeus-python/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 419, in evaluate_expression
    compiled = compile(_expression_to_evaluate(expression), '<string>', 'eval')
  File "<string>", line 1
    function variables_repr_data,function variables_repr_metada = (get_ipython().display_formatter.format(function variables))
             ^
SyntaxError: invalid syntax
```

if client does a silly thing of passing not-a-variable to the kernel debugger (see https://github.com/jupyterlab/jupyterlab/issues/11009). While the error is on the client side in the first place, should the debugger reject this nicely rather than error out?

**Comment by JohanMabille** [comment]
Ah indeed, kernels should filter invalid expressions since they are language specific. I will make a fix or the next release of xeus-python.
